blueprint:
  name: IKEA Bilresa (with scroll wheel)
  description: "Control dimming with IKEA Bilresa remote with scroll wheel"
  domain: automation
  input:
    button_1:
      name: Button 1
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_2:
      name: Button 2
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_3:
      name: Button 3
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_4:
      name: Button 4
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_5:
      name: Button 5
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_6:
      name: Button 6
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_7:
      name: Button 7
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_8:
      name: Button 8
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    button_9:
      name: Button 9
      selector:
        entity:
          filter:
            - domain: event
          multiple: false
          reorder: false
    target_dimming_1:
      name: Dimming Value
      selector:
        entity:
          filter:
            - domain: input_number
    target_dimming_2:
      name: Dimming Value
      selector:
        entity:
          filter:
            - domain: input_number
    target_dimming_3:
      name: Dimming Value 
      default: []
      selector:
        entity:
          filter:
            - domain: input_number
    dimming_step:
      name: Dimming Step
      description: Dimming Step
      default: 5
      selector:
        number:
          min: 1.0
          max: 10.0
          step: 1.0
          unit_of_measurement: "%"
          mode: slider
    action_group_1_single:
      name: "Action Group 1 - Single Press"
      default: []
      selector:
        action: {}
    action_group_1_double:
      name: "Action Group 1 - Double Press"
      default: []
      selector:
        action: {}
    action_group_1_triple:
      name: "Action Group 1 - Triple Press"
      default: []
      selector:
        action: {}
    action_group_1_long_press:
      name: "Action Group 1 - Long Press"
      default: []
      selector:
        action: {}
    action_group_1_long_press_release:
      name: "Action Group 1 - Long Press Release"
      default: []
      selector:
        action: {}
    action_group_2_single:
      name: "Action Group 2 - Single Press"
      default: []
      selector:
        action: {}
    action_group_2_double:
      name: "Action Group 2 - Double Press"
      default: []
      selector:
        action: {}
    action_group_2_triple:
      name: "Action Group 2 - Triple Press"
      default: []
      selector:
        action: {}
    action_group_2_long_press:
      name: "Action Group 2 - Long Press"
      default: []
      selector:
        action: {}
    action_group_2_long_press_release:
      name: "Action Group 2 - Long Press Release"
      default: []
      selector:
        action: {}
    action_group_3_single:
      name: "Action Group 3 - Single Press"
      default: []
      selector:
        action: {}
    action_group_3_double:
      name: "Action Group 3 - Double Press"
      default: []
      selector:
        action: {}
    action_group_3_triple:
      name: "Action Group 3 - Triple Press"
      default: []
      selector:
        action: {}
    action_group_3_long_press:
      name: "Action Group 3 - Long Press"
      default: []
      selector:
        action: {}
    action_group_3_long_press_release:
      name: "Action Group 3 - Long Press Release"
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1
    id: btn1
  - platform: state
    entity_id: !input button_2
    id: btn2
  - platform: state
    entity_id: !input button_3
    id: btn3
  - platform: state
    entity_id: !input button_4
    id: btn4
  - platform: state
    entity_id: !input button_5
    id: btn5
  - platform: state
    entity_id: !input button_6
    id: btn6
  - platform: state
    entity_id: !input button_7
    id: btn7
  - platform: state
    entity_id: !input button_8
    id: btn8
  - platform: state
    entity_id: !input button_9
    id: btn9

action:
  - variables:
      dimming_1: !input target_dimming_1
      dimming_2: !input target_dimming_2
      dimming_3: !input target_dimming_3
      step: !input dimming_step
      group_number: >
        {% if trigger.id in ['btn1', 'btn2', 'btn3'] %}
          1
        {% elif trigger.id in ['btn4', 'btn5', 'btn6'] %}
          2
        {% else %}
          3
        {% endif %}
      target_group: >
        {% if trigger.id in ['btn1', 'btn2', 'btn3'] %}
          {{ dimming_1 }}
        {% elif trigger.id in ['btn4', 'btn5', 'btn6'] %}
          {{ dimming_2 }}
        {% else %}
          {{ dimming_3 }}
        {% endif %}
      action_type_raw: "{{ trigger.to_state.attributes.event_type }}"
      action_type: >
        {% if action_type_raw == 'multi_press_1' %}
          single
        {% elif action_type_raw == 'multi_press_2' %}
          double
        {% elif action_type_raw == 'multi_press_3' %}
          triple
        {% elif action_type_raw == 'long_press' %}
          long_press
        {% elif action_type_raw == 'long_release' %}
          long_press_release
        {% endif %}
    
      dimming_amount: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn1', 'btn4', 'btn7'] }}"
          - condition: template
            value_template: "{{ target_group != [] }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: "{{ target_group }}"
            data:
              value: "{{ min(100, (states(target_group) | float(0)) + (dimming_amount * step)) }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn2', 'btn5', 'btn8'] }}"
          - condition: template
            value_template: "{{ target_group != [] }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: "{{ target_group }}"
            data:
              value: "{{ max(0, (states(target_group) | float(0)) - (dimming_amount * step)) }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['btn3', 'btn6', 'btn9'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 1 and action_type == 'single' }}"
                sequence: !input action_group_1_single
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 1 and action_type == 'double' }}"
                sequence: !input action_group_1_double
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 1 and action_type == 'triple' }}"
                sequence: !input action_group_1_triple
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 1 and action_type == 'long_press' }}"
                sequence: !input action_group_1_long_press
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 1 and action_type == 'long_press_release' }}"
                sequence: !input action_group_1_long_press_release
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 2 and action_type == 'single' }}"
                sequence: !input action_group_2_single
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 2 and action_type == 'double' }}"
                sequence: !input action_group_2_double
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 2 and action_type == 'triple' }}"
                sequence: !input action_group_2_triple
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 2 and action_type == 'long_press' }}"
                sequence: !input action_group_2_long_press
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 2 and action_type == 'long_press_release' }}"
                sequence: !input action_group_2_long_press_release
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 3 and action_type == 'single' }}"
                sequence: !input action_group_3_single
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 3 and action_type == 'double' }}"
                sequence: !input action_group_3_double
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 3 and action_type == 'triple' }}"
                sequence: !input action_group_3_triple
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 3 and action_type == 'long_press' }}"
                sequence: !input action_group_3_long_press
              - conditions:
                  - condition: template
                    value_template: "{{ group_number == 3 and action_type == 'long_press_release' }}"
                sequence: !input action_group_3_long_press_release
    default: [] 