blueprint:
  name: test
  description: test
  domain: automation
  input:
    dimming_value:
      name: Dimming Value
      description: Input number entity for dimming value
      selector:
        entity:
          filter:
            - domain: input_number
          multiple: false
    light_entity:
      name: Light
      description: Light entity to control
      selector:
        entity:
          filter:
            - domain: light
          multiple: false
    light_temperature:
      name: Light Temperature
      description: Light color temperature value
      selector:
        number:
          min: 2000
          max: 6500
          step: 1
          unit_of_measurement: K
    base_brightness:
      name: Base Brightness
      description: Minimum brightness in percent
      default: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    peak_brightness:
      name: Peak Brightness
      description: Maximum brightness in percent
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    switch_entity:
      name: Switch (input boolean)
      description: Switch entity to trigger the automation
      selector:
        entity:
          filter:
            - domain: input_boolean
          multiple: false

trigger:
  - platform: state
    entity_id: !input switch_entity
  - platform: state
    entity_id: !input dimming_value

condition:
  - condition: state
    entity_id: !input switch_entity
    state: "on"

action:
  - variables:
      dimming_entity: !input dimming_value
      dimming_pct: "{{ states(dimming_entity) | float(0) }}"
      base_brightness: !input base_brightness
      peak_brightness: !input peak_brightness
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_pct: "{{ (dimming_pct * (peak_brightness - base_brightness) / 100 + base_brightness) | round(0) }}"
      kelvin: !input light_temperature
